@csrf
<div class="grid gap-4 sm:grid-cols-2">
    <div><label class="block text-sm font-medium">Asset Code</label><input name="asset_code" value="{{ old('asset_code', $asset->asset_code ?? '') }}" placeholder="Auto if empty" class="mt-1 w-full rounded-md border-gray-300"></div>
    <div><label class="block text-sm font-medium">Name</label><input name="name" value="{{ old('name', $asset->name ?? '') }}" class="mt-1 w-full rounded-md border-gray-300" required></div>
    <div><label class="block text-sm font-medium">Category</label><input name="category" value="{{ old('category', $asset->category ?? '') }}" class="mt-1 w-full rounded-md border-gray-300" required></div>
    <div><label class="block text-sm font-medium">Location</label><input name="location" value="{{ old('location', $asset->location ?? '') }}" class="mt-1 w-full rounded-md border-gray-300"></div>
    <div><label class="block text-sm font-medium">Brand</label><input name="brand" value="{{ old('brand', $asset->brand ?? '') }}" class="mt-1 w-full rounded-md border-gray-300"></div>
    <div><label class="block text-sm font-medium">Model</label><input name="model" value="{{ old('model', $asset->model ?? '') }}" class="mt-1 w-full rounded-md border-gray-300"></div>
    <div><label class="block text-sm font-medium">Serial Number</label><input name="serial_number" value="{{ old('serial_number', $asset->serial_number ?? '') }}" class="mt-1 w-full rounded-md border-gray-300"></div>
    <div><label class="block text-sm font-medium">Purchase Price</label><input type="number" step="0.01" name="purchase_price" value="{{ old('purchase_price', $asset->purchase_price ?? 0) }}" class="mt-1 w-full rounded-md border-gray-300"></div>
    <div><label class="block text-sm font-medium">Purchase Store</label><input name="purchase_store_name" value="{{ old('purchase_store_name', $asset->purchaseStore->name ?? '') }}" class="mt-1 w-full rounded-md border-gray-300"></div>
    <div><label class="block text-sm font-medium">Supplier</label><input name="supplier_name" value="{{ old('supplier_name', $asset->supplier->name ?? '') }}" class="mt-1 w-full rounded-md border-gray-300"></div>
    <div><label class="block text-sm font-medium">Service Contact</label><select name="service_contact_id" class="mt-1 w-full rounded-md border-gray-300"><option value="">Select</option>@foreach($serviceContacts as $contact)<option value="{{ $contact->id }}" @selected((string) old('service_contact_id', $asset->service_contact_id ?? '') === (string) $contact->id)>{{ $contact->name }}</option>@endforeach</select></div>
    <div><label class="block text-sm font-medium">Purchase Date</label><input type="date" name="purchase_date" value="{{ old('purchase_date', isset($asset) && $asset->purchase_date ? $asset->purchase_date->format('Y-m-d') : '') }}" class="mt-1 w-full rounded-md border-gray-300"></div>
    <div><label class="block text-sm font-medium">Warranty Expires</label><input type="date" name="warranty_expires_at" value="{{ old('warranty_expires_at', isset($asset) && $asset->warranty_expires_at ? $asset->warranty_expires_at->format('Y-m-d') : '') }}" class="mt-1 w-full rounded-md border-gray-300"></div>
    <div><label class="block text-sm font-medium">Maintenance Interval (Months)</label><input type="number" min="1" max="120" name="maintenance_interval_months" value="{{ old('maintenance_interval_months', $asset->maintenance_interval_months ?? 3) }}" class="mt-1 w-full rounded-md border-gray-300" required></div>
    <div><label class="block text-sm font-medium">Status</label><select name="status" class="mt-1 w-full rounded-md border-gray-300">@foreach($statuses as $status)<option value="{{ $status->value }}" @selected(old('status', isset($asset) ? $asset->status->value : 'available') === $status->value)>{{ $status->label() }}</option>@endforeach</select></div>
    <div><label class="block text-sm font-medium">Condition</label><select name="condition" class="mt-1 w-full rounded-md border-gray-300">@foreach($conditions as $condition)<option value="{{ $condition->value }}" @selected(old('condition', isset($asset) ? $asset->condition->value : 'good') === $condition->value)>{{ $condition->label() }}</option>@endforeach</select></div>
    <div class="sm:col-span-2"><label class="block text-sm font-medium">Notes</label><textarea name="notes" class="mt-1 w-full rounded-md border-gray-300">{{ old('notes', $asset->notes ?? '') }}</textarea></div>
</div>
<div class="mt-6 flex items-center gap-3"><button class="rounded-md bg-gray-900 px-4 py-2 text-sm font-semibold text-white">Save Asset</button><a href="{{ route('assets.index') }}" class="text-sm text-gray-600">Cancel</a></div>
